/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.24
 * Generated at: 2026-08-14 02:32:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.Map;
import org.todolist.model.Task;
import org.todolist.model.Category;
import org.todolist.model.Tag;
import org.todolist.model.SubTask;
import org.todolist.model.Reminder;

public final class tareas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(10);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("org.todolist.model.Task");
    _jspx_imports_classes.add("org.todolist.model.Category");
    _jspx_imports_classes.add("org.todolist.model.Tag");
    _jspx_imports_classes.add("org.todolist.model.SubTask");
    _jspx_imports_classes.add("org.todolist.model.Reminder");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    List<Task> tareas =
            (List<Task>) request.getAttribute("tareas");

    List<Category> categorias =
            (List<Category>) request.getAttribute("categorias");

    List<Tag> etiquetas =
            (List<Tag>) request.getAttribute("etiquetas");

    Task tareaEditar =
            (Task) request.getAttribute("tareaEditar");

    List<Integer> etiquetasTarea =
            (List<Integer>) request.getAttribute("etiquetasTarea");

    Map<Integer, List<SubTask>> subtareasPorTarea =
            (Map<Integer, List<SubTask>>)
                    request.getAttribute("subtareasPorTarea");

    Map<Integer, List<Reminder>> recordatoriosPorTarea =
            (Map<Integer, List<Reminder>>)
                    request.getAttribute("recordatoriosPorTarea");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"viewport\"\r\n");
      out.write("          content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <title>Mis tareas - ToDoList</title>\r\n");
      out.write("\r\n");
      out.write("    <link\r\n");
      out.write("            rel=\"stylesheet\"\r\n");
      out.write("            href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/tareas.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ============================================================\r\n");
      out.write("     CABECERA\r\n");
      out.write("     ============================================================ -->\r\n");
      out.write("\r\n");
      out.write("<header class=\"barra-superior\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"barra-contenido\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("\r\n");
      out.write("            <span class=\"logo-icono\">✓</span>\r\n");
      out.write("\r\n");
      out.write("            <span>ToDoList</span>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"usuario-menu\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Accesos rapidos -->\r\n");
      out.write("            <nav class=\"accesos-rapidos\">\r\n");
      out.write("\r\n");
      out.write("                <a\r\n");
      out.write("                    href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/tareas\"\r\n");
      out.write("                    class=\"acceso-rapido\">\r\n");
      out.write("                    Mis tareas\r\n");
      out.write("                </a>\r\n");
      out.write("\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/tags\"\r\n");
      out.write("                   class=\"acceso-rapido\">\r\n");
      out.write("                    Tags\r\n");
      out.write("                </a>\r\n");
      out.write("\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/categorias\"\r\n");
      out.write("                   class=\"acceso-rapido\">\r\n");
      out.write("                    Categorías\r\n");
      out.write("                </a>\r\n");
      out.write("\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/subtareas\"\r\n");
      out.write("                   class=\"acceso-rapido\">\r\n");
      out.write("                    Subtareas\r\n");
      out.write("                </a>\r\n");
      out.write("\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/recordatorios\"\r\n");
      out.write("                   class=\"acceso-rapido\">\r\n");
      out.write("                    Recordatorios\r\n");
      out.write("                </a>\r\n");
      out.write("\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/timelog\"\r\n");
      out.write("                   class=\"acceso-rapido\">\r\n");
      out.write("                    Timelog\r\n");
      out.write("                </a>\r\n");
      out.write("\r\n");
      out.write("            </nav>\r\n");
      out.write("\r\n");
      out.write("            <a\r\n");
      out.write("                    class=\"boton-salir\"\r\n");
      out.write("                    href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/usuario?accion=logout\">\r\n");
      out.write("\r\n");
      out.write("                Cerrar sesión\r\n");
      out.write("\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ============================================================\r\n");
      out.write("     CONTENIDO PRINCIPAL\r\n");
      out.write("     ============================================================ -->\r\n");
      out.write("\r\n");
      out.write("<main class=\"contenedor-principal\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ========================================================\r\n");
      out.write("         ENCABEZADO\r\n");
      out.write("         ======================================================== -->\r\n");
      out.write("\r\n");
      out.write("    <section class=\"encabezado-pagina\">\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("\r\n");
      out.write("            <h1>\r\n");
      out.write("                Mis tareas\r\n");
      out.write("            </h1>\r\n");
      out.write("\r\n");
      out.write("            <p>\r\n");
      out.write("                Organiza tus pendientes y mantén el control de tu día.\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"contador-tareas\">\r\n");
      out.write("\r\n");
      out.write("            <span class=\"contador-numero\">\r\n");
      out.write("                ");
      out.print( tareas != null ? tareas.size() : 0 );
      out.write("\r\n");
      out.write("            </span>\r\n");
      out.write("\r\n");
      out.write("            <span class=\"contador-texto\">\r\n");
      out.write("                tareas\r\n");
      out.write("            </span>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ========================================================\r\n");
      out.write("         FORMULARIO\r\n");
      out.write("         ======================================================== -->\r\n");
      out.write("\r\n");
      out.write("    <section class=\"formulario-tarea\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 if (tareaEditar != null) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- ====================================================\r\n");
      out.write("             EDITAR\r\n");
      out.write("             ==================================================== -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"titulo-formulario\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"icono-formulario\">\r\n");
      out.write("                ✎\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("\r\n");
      out.write("                <h2>\r\n");
      out.write("                    Editar tarea\r\n");
      out.write("                </h2>\r\n");
      out.write("\r\n");
      out.write("                <p>\r\n");
      out.write("                    Modifica la información de tu tarea.\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <form\r\n");
      out.write("                action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/tareas\"\r\n");
      out.write("                method=\"post\"\r\n");
      out.write("                class=\"form-tarea\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <input\r\n");
      out.write("                    type=\"hidden\"\r\n");
      out.write("                    name=\"accion\"\r\n");
      out.write("                    value=\"actualizar\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <input\r\n");
      out.write("                    type=\"hidden\"\r\n");
      out.write("                    name=\"id\"\r\n");
      out.write("                    value=\"");
      out.print( tareaEditar.getId() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"grid-formulario\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- TÍTULO -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"campo campo-completo\">\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"titulo\">\r\n");
      out.write("                        Título\r\n");
      out.write("                    </label>\r\n");
      out.write("\r\n");
      out.write("                    <input\r\n");
      out.write("                            type=\"text\"\r\n");
      out.write("                            id=\"titulo\"\r\n");
      out.write("                            name=\"titulo\"\r\n");
      out.write("                            maxlength=\"100\"\r\n");
      out.write("                            value=\"");
      out.print( tareaEditar.getTitulo() );
      out.write("\"\r\n");
      out.write("                            required>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- DESCRIPCIÓN -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"campo campo-completo\">\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"descripcion\">\r\n");
      out.write("                        Descripción\r\n");
      out.write("                    </label>\r\n");
      out.write("\r\n");
      out.write("                    <textarea\r\n");
      out.write("                            id=\"descripcion\"\r\n");
      out.write("                            name=\"descripcion\"\r\n");
      out.write("                            rows=\"4\">");
      out.print( tareaEditar.getDescripcion() != null
                            ? tareaEditar.getDescripcion()
                            : "" );
      out.write("</textarea>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- FECHA -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"campo\">\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"fechaLimite\">\r\n");
      out.write("                        Fecha límite\r\n");
      out.write("                    </label>\r\n");
      out.write("\r\n");
      out.write("                    <input\r\n");
      out.write("                            type=\"date\"\r\n");
      out.write("                            id=\"fechaLimite\"\r\n");
      out.write("                            name=\"fechaLimite\"\r\n");
      out.write("                            value=\"");
      out.print( tareaEditar.getFechaLimite() != null
                                    ? tareaEditar.getFechaLimite()
                                    : "" );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- PRIORIDAD -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"campo\">\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"prioridad\">\r\n");
      out.write("                        Prioridad\r\n");
      out.write("                    </label>\r\n");
      out.write("\r\n");
      out.write("                    <select\r\n");
      out.write("                            id=\"prioridad\"\r\n");
      out.write("                            name=\"prioridad\"\r\n");
      out.write("                            required>\r\n");
      out.write("\r\n");
      out.write("                        <option\r\n");
      out.write("                                value=\"ALTA\"\r\n");
      out.write("                                ");
      out.print( tareaEditar.getPrioridad() != null
                                        && tareaEditar.getPrioridad().name().equals("ALTA")
                                        ? "selected"
                                        : "" );
      out.write(">\r\n");
      out.write("                            Alta\r\n");
      out.write("                        </option>\r\n");
      out.write("\r\n");
      out.write("                        <option\r\n");
      out.write("                                value=\"MEDIA\"\r\n");
      out.write("                                ");
      out.print( tareaEditar.getPrioridad() != null
                                        && tareaEditar.getPrioridad().name().equals("MEDIA")
                                        ? "selected"
                                        : "" );
      out.write(">\r\n");
      out.write("                            Media\r\n");
      out.write("                        </option>\r\n");
      out.write("\r\n");
      out.write("                        <option\r\n");
      out.write("                                value=\"BAJA\"\r\n");
      out.write("                                ");
      out.print( tareaEditar.getPrioridad() != null
                                        && tareaEditar.getPrioridad().name().equals("BAJA")
                                        ? "selected"
                                        : "" );
      out.write(">\r\n");
      out.write("                            Baja\r\n");
      out.write("                        </option>\r\n");
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- ESTADO -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"campo\">\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"estado\">\r\n");
      out.write("                        Estado\r\n");
      out.write("                    </label>\r\n");
      out.write("\r\n");
      out.write("                    <select\r\n");
      out.write("                            id=\"estado\"\r\n");
      out.write("                            name=\"estado\"\r\n");
      out.write("                            required>\r\n");
      out.write("\r\n");
      out.write("                        <option\r\n");
      out.write("                                value=\"PENDIENTE\"\r\n");
      out.write("                                ");
      out.print( tareaEditar.getEstado() != null
                                        && tareaEditar.getEstado().name().equals("PENDIENTE")
                                        ? "selected"
                                        : "" );
      out.write(">\r\n");
      out.write("                            Pendiente\r\n");
      out.write("                        </option>\r\n");
      out.write("\r\n");
      out.write("                        <option\r\n");
      out.write("                                value=\"EN_PROGRESO\"\r\n");
      out.write("                                ");
      out.print( tareaEditar.getEstado() != null
                                        && tareaEditar.getEstado().name().equals("EN_PROGRESO")
                                        ? "selected"
                                        : "" );
      out.write(">\r\n");
      out.write("                            En progreso\r\n");
      out.write("                        </option>\r\n");
      out.write("\r\n");
      out.write("                        <option\r\n");
      out.write("                                value=\"COMPLETADA\"\r\n");
      out.write("                                ");
      out.print( tareaEditar.getEstado() != null
                                        && tareaEditar.getEstado().name().equals("COMPLETADA")
                                        ? "selected"
                                        : "" );
      out.write(">\r\n");
      out.write("                            Completada\r\n");
      out.write("                        </option>\r\n");
      out.write("\r\n");
      out.write("                        <option\r\n");
      out.write("                                value=\"VENCIDA\"\r\n");
      out.write("                                ");
      out.print( tareaEditar.getEstado() != null
                                        && tareaEditar.getEstado().name().equals("VENCIDA")
                                        ? "selected"
                                        : "" );
      out.write(">\r\n");
      out.write("                            Vencida\r\n");
      out.write("                        </option>\r\n");
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- PROGRESO -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"campo\">\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"progreso\">\r\n");
      out.write("                        Progreso (%)\r\n");
      out.write("                    </label>\r\n");
      out.write("\r\n");
      out.write("                    <input\r\n");
      out.write("                            type=\"number\"\r\n");
      out.write("                            id=\"progreso\"\r\n");
      out.write("                            name=\"progreso\"\r\n");
      out.write("                            min=\"0\"\r\n");
      out.write("                            max=\"100\"\r\n");
      out.write("                            value=\"");
      out.print( tareaEditar.getProgreso() );
      out.write("\"\r\n");
      out.write("                            required>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- CATEGORÍA -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"campo\">\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"idCategoria\">\r\n");
      out.write("                        Categoría\r\n");
      out.write("                    </label>\r\n");
      out.write("\r\n");
      out.write("                    <select\r\n");
      out.write("                            id=\"idCategoria\"\r\n");
      out.write("                            name=\"idCategoria\">\r\n");
      out.write("\r\n");
      out.write("                        <option value=\"\">\r\n");
      out.write("                            Sin categoría\r\n");
      out.write("                        </option>\r\n");
      out.write("\r\n");
      out.write("                        ");
 if (categorias != null) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        ");
 for (Category categoria : categorias) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <option\r\n");
      out.write("                                value=\"");
      out.print( categoria.getId() );
      out.write("\"\r\n");
      out.write("                                ");
      out.print( tareaEditar.getIdCategoria() != null
                                        && tareaEditar.getIdCategoria()
                                        == categoria.getId()
                                        ? "selected"
                                        : "" );
      out.write(">\r\n");
      out.write("\r\n");
      out.write("                            ");
      out.print( categoria.getNombre() );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </option>\r\n");
      out.write("\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- ETIQUETA -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"campo\">\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"idEtiqueta\">\r\n");
      out.write("                        Etiqueta\r\n");
      out.write("                    </label>\r\n");
      out.write("\r\n");
      out.write("                    <select\r\n");
      out.write("                            id=\"idEtiqueta\"\r\n");
      out.write("                            name=\"idEtiqueta\">\r\n");
      out.write("\r\n");
      out.write("                        <option value=\"\">\r\n");
      out.write("                            Sin etiqueta\r\n");
      out.write("                        </option>\r\n");
      out.write("\r\n");
      out.write("                        ");
 if (etiquetas != null) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        ");
 for (Tag etiqueta : etiquetas) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <option\r\n");
      out.write("                                value=\"");
      out.print( etiqueta.getIdEtiqueta() );
      out.write("\"\r\n");
      out.write("                                ");
      out.print( etiquetasTarea != null
                                        && etiquetasTarea.contains(
                                        etiqueta.getIdEtiqueta()
                                )
                                        ? "selected"
                                        : "" );
      out.write(">\r\n");
      out.write("\r\n");
      out.write("                            ");
      out.print( etiqueta.getNombre() );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </option>\r\n");
      out.write("\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"acciones-formulario\">\r\n");
      out.write("\r\n");
      out.write("                <button\r\n");
      out.write("                        type=\"submit\"\r\n");
      out.write("                        class=\"boton boton-principal\">\r\n");
      out.write("\r\n");
      out.write("                    Guardar cambios\r\n");
      out.write("\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <a\r\n");
      out.write("                        href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/tareas\"\r\n");
      out.write("                        class=\"boton boton-secundario\">\r\n");
      out.write("\r\n");
      out.write("                    Cancelar\r\n");
      out.write("\r\n");
      out.write("                </a>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- ====================================================\r\n");
      out.write("             CREAR\r\n");
      out.write("             ==================================================== -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"titulo-formulario\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"icono-formulario\">\r\n");
      out.write("                +\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("\r\n");
      out.write("                <h2>\r\n");
      out.write("                    Agregar tarea\r\n");
      out.write("                </h2>\r\n");
      out.write("\r\n");
      out.write("                <p>\r\n");
      out.write("                    Crea una nueva tarea para mantener todo organizado.\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <form\r\n");
      out.write("                action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/tareas\"\r\n");
      out.write("                method=\"post\"\r\n");
      out.write("                class=\"form-tarea\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <input\r\n");
      out.write("                    type=\"hidden\"\r\n");
      out.write("                    name=\"accion\"\r\n");
      out.write("                    value=\"crear\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"grid-formulario\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- TÍTULO -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"campo campo-completo\">\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"titulo\">\r\n");
      out.write("                        Título\r\n");
      out.write("                    </label>\r\n");
      out.write("\r\n");
      out.write("                    <input\r\n");
      out.write("                            type=\"text\"\r\n");
      out.write("                            id=\"titulo\"\r\n");
      out.write("                            name=\"titulo\"\r\n");
      out.write("                            maxlength=\"100\"\r\n");
      out.write("                            placeholder=\"Ej. Terminar proyecto de programación\"\r\n");
      out.write("                            required>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- DESCRIPCIÓN -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"campo campo-completo\">\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"descripcion\">\r\n");
      out.write("                        Descripción\r\n");
      out.write("                    </label>\r\n");
      out.write("\r\n");
      out.write("                    <textarea\r\n");
      out.write("                            id=\"descripcion\"\r\n");
      out.write("                            name=\"descripcion\"\r\n");
      out.write("                            rows=\"4\"\r\n");
      out.write("                            placeholder=\"Describe brevemente la tarea...\"></textarea>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- FECHA -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"campo\">\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"fechaLimite\">\r\n");
      out.write("                        Fecha límite\r\n");
      out.write("                    </label>\r\n");
      out.write("\r\n");
      out.write("                    <input\r\n");
      out.write("                            type=\"date\"\r\n");
      out.write("                            id=\"fechaLimite\"\r\n");
      out.write("                            name=\"fechaLimite\">\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- PRIORIDAD -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"campo\">\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"prioridad\">\r\n");
      out.write("                        Prioridad\r\n");
      out.write("                    </label>\r\n");
      out.write("\r\n");
      out.write("                    <select\r\n");
      out.write("                            id=\"prioridad\"\r\n");
      out.write("                            name=\"prioridad\"\r\n");
      out.write("                            required>\r\n");
      out.write("\r\n");
      out.write("                        <option value=\"ALTA\">\r\n");
      out.write("                            Alta\r\n");
      out.write("                        </option>\r\n");
      out.write("\r\n");
      out.write("                        <option\r\n");
      out.write("                                value=\"MEDIA\"\r\n");
      out.write("                                selected>\r\n");
      out.write("                            Media\r\n");
      out.write("                        </option>\r\n");
      out.write("\r\n");
      out.write("                        <option value=\"BAJA\">\r\n");
      out.write("                            Baja\r\n");
      out.write("                        </option>\r\n");
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- CATEGORÍA -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"campo\">\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"idCategoria\">\r\n");
      out.write("                        Categoría\r\n");
      out.write("                    </label>\r\n");
      out.write("\r\n");
      out.write("                    <select\r\n");
      out.write("                            id=\"idCategoria\"\r\n");
      out.write("                            name=\"idCategoria\">\r\n");
      out.write("\r\n");
      out.write("                        <option value=\"\">\r\n");
      out.write("                            Sin categoría\r\n");
      out.write("                        </option>\r\n");
      out.write("\r\n");
      out.write("                        ");
 if (categorias != null) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        ");
 for (Category categoria : categorias) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <option\r\n");
      out.write("                                value=\"");
      out.print( categoria.getId() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                            ");
      out.print( categoria.getNombre() );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </option>\r\n");
      out.write("\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- ETIQUETA -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"campo\">\r\n");
      out.write("\r\n");
      out.write("                    <label for=\"idEtiqueta\">\r\n");
      out.write("                        Etiqueta\r\n");
      out.write("                    </label>\r\n");
      out.write("\r\n");
      out.write("                    <select\r\n");
      out.write("                            id=\"idEtiqueta\"\r\n");
      out.write("                            name=\"idEtiqueta\">\r\n");
      out.write("\r\n");
      out.write("                        <option value=\"\">\r\n");
      out.write("                            Sin etiqueta\r\n");
      out.write("                        </option>\r\n");
      out.write("\r\n");
      out.write("                        ");
 if (etiquetas != null) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        ");
 for (Tag etiqueta : etiquetas) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <option\r\n");
      out.write("                                value=\"");
      out.print( etiqueta.getIdEtiqueta() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                            ");
      out.print( etiqueta.getNombre() );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </option>\r\n");
      out.write("\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"acciones-formulario\">\r\n");
      out.write("\r\n");
      out.write("                <button\r\n");
      out.write("                        type=\"submit\"\r\n");
      out.write("                        class=\"boton boton-principal\">\r\n");
      out.write("\r\n");
      out.write("                    + Agregar tarea\r\n");
      out.write("\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ========================================================\r\n");
      out.write("         LISTA DE TAREAS\r\n");
      out.write("         ======================================================== -->\r\n");
      out.write("\r\n");
      out.write("    <section class=\"lista-tareas\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"titulo-lista\">\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("\r\n");
      out.write("                <h2>\r\n");
      out.write("                    Tus tareas\r\n");
      out.write("                </h2>\r\n");
      out.write("\r\n");
      out.write("                <p>\r\n");
      out.write("                    Revisa el estado de tus actividades.\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 if (tareas != null && !tareas.isEmpty()) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"grid-tareas\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            ");
 for (Task tarea : tareas) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <article class=\"tarea\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- ==============================================\r\n");
      out.write("                     CABECERA TARJETA\r\n");
      out.write("                     ============================================== -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"tarea-cabecera\">\r\n");
      out.write("\r\n");
      out.write("                    <h3>\r\n");
      out.write("                        ");
      out.print( tarea.getTitulo() );
      out.write("\r\n");
      out.write("                    </h3>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"acciones-tarea\">\r\n");
      out.write("\r\n");
      out.write("                        <form\r\n");
      out.write("                                action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/tareas\"\r\n");
      out.write("                                method=\"get\">\r\n");
      out.write("\r\n");
      out.write("                            <input\r\n");
      out.write("                                    type=\"hidden\"\r\n");
      out.write("                                    name=\"accion\"\r\n");
      out.write("                                    value=\"editar\">\r\n");
      out.write("\r\n");
      out.write("                            <input\r\n");
      out.write("                                    type=\"hidden\"\r\n");
      out.write("                                    name=\"id\"\r\n");
      out.write("                                    value=\"");
      out.print( tarea.getId() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                            <button\r\n");
      out.write("                                    type=\"submit\"\r\n");
      out.write("                                    class=\"boton-icono editar\"\r\n");
      out.write("                                    title=\"Editar tarea\">\r\n");
      out.write("\r\n");
      out.write("                                ✎\r\n");
      out.write("\r\n");
      out.write("                            </button>\r\n");
      out.write("\r\n");
      out.write("                        </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <form\r\n");
      out.write("                                action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/tareas\"\r\n");
      out.write("                                method=\"post\"\r\n");
      out.write("                                onsubmit=\"return confirm('¿Está seguro de que desea eliminar esta tarea?');\">\r\n");
      out.write("\r\n");
      out.write("                            <input\r\n");
      out.write("                                    type=\"hidden\"\r\n");
      out.write("                                    name=\"accion\"\r\n");
      out.write("                                    value=\"eliminar\">\r\n");
      out.write("\r\n");
      out.write("                            <input\r\n");
      out.write("                                    type=\"hidden\"\r\n");
      out.write("                                    name=\"id\"\r\n");
      out.write("                                    value=\"");
      out.print( tarea.getId() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                            <button\r\n");
      out.write("                                    type=\"submit\"\r\n");
      out.write("                                    class=\"boton-icono eliminar\"\r\n");
      out.write("                                    title=\"Eliminar tarea\">\r\n");
      out.write("\r\n");
      out.write("                                🗑\r\n");
      out.write("\r\n");
      out.write("                            </button>\r\n");
      out.write("\r\n");
      out.write("                        </form>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- ==============================================\r\n");
      out.write("                     DESCRIPCIÓN\r\n");
      out.write("                     ============================================== -->\r\n");
      out.write("\r\n");
      out.write("                <p class=\"descripcion-tarea\">\r\n");
      out.write("\r\n");
      out.write("                    ");
      out.print( tarea.getDescripcion() != null
                            && !tarea.getDescripcion().isBlank()
                            ? tarea.getDescripcion()
                            : "Sin descripción" );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- ==============================================\r\n");
      out.write("                     BADGES\r\n");
      out.write("                     ============================================== -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"badges\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <span class=\"badge prioridad-");
      out.print( tarea.getPrioridad() != null
                            ? tarea.getPrioridad().name().toLowerCase()
                            : "sin-prioridad" );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                        ");
      out.print( tarea.getPrioridad() != null
                                ? tarea.getPrioridad().name()
                                : "Sin prioridad" );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </span>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <span class=\"badge estado-");
      out.print( tarea.getEstado() != null
                            ? tarea.getEstado().name().toLowerCase()
                            : "sin-estado" );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                        ");
      out.print( tarea.getEstado() != null
                                ? tarea.getEstado().name().replace("_", " ")
                                : "Sin estado" );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </span>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- ==============================================\r\n");
      out.write("                     INFORMACIÓN\r\n");
      out.write("                     ============================================== -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"informacion-tarea\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"dato-tarea\">\r\n");
      out.write("\r\n");
      out.write("                        <span class=\"dato-label\">\r\n");
      out.write("                            Fecha límite\r\n");
      out.write("                        </span>\r\n");
      out.write("\r\n");
      out.write("                        <span class=\"dato-valor\">\r\n");
      out.write("\r\n");
      out.write("                            ");
      out.print( tarea.getFechaLimite() != null
                                    ? tarea.getFechaLimite()
                                    : "Sin fecha" );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"dato-tarea\">\r\n");
      out.write("\r\n");
      out.write("                        <span class=\"dato-label\">\r\n");
      out.write("                            Categoría\r\n");
      out.write("                        </span>\r\n");
      out.write("\r\n");
      out.write("                        <span class=\"dato-valor\">\r\n");
      out.write("\r\n");
      out.write("                            ");

                                String nombreCategoria =
                                        "Sin categoría";

                                if (tarea.getIdCategoria() != null
                                        && categorias != null) {

                                    for (Category categoria :
                                            categorias) {

                                        if (categoria.getId()
                                                == tarea.getIdCategoria()) {

                                            nombreCategoria =
                                                    categoria.getNombre();

                                            break;
                                        }
                                    }
                                }
                            
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            ");
      out.print( nombreCategoria );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"dato-tarea\">\r\n");
      out.write("\r\n");
      out.write("                        <span class=\"dato-label\">\r\n");
      out.write("                            Etiqueta\r\n");
      out.write("                        </span>\r\n");
      out.write("\r\n");
      out.write("                        <span class=\"dato-valor\">\r\n");
      out.write("\r\n");
      out.write("                            ");

                                List<Integer> idsEtiquetas =
                                        (List<Integer>)
                                                request.getAttribute(
                                                        "etiquetasTarea_"
                                                                + tarea.getId()
                                                );

                                boolean tieneEtiqueta =
                                        false;
                            
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            ");
 if (idsEtiquetas != null
                                    && etiquetas != null) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                ");
 for (Integer idEtiqueta :
                                        idsEtiquetas) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                    ");
 for (Tag etiqueta :
                                            etiquetas) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        ");
 if (etiqueta.getIdEtiqueta()
                                                == idEtiqueta) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                            ");
      out.print( etiqueta.getNombre() );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                            ");

                                                tieneEtiqueta = true;
                                            
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            ");
 if (!tieneEtiqueta) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                Sin etiqueta\r\n");
      out.write("\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- ==============================================\r\n");
      out.write("                     PROGRESO\r\n");
      out.write("                     ============================================== -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"progreso\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"progreso-cabecera\">\r\n");
      out.write("\r\n");
      out.write("                        <span>\r\n");
      out.write("                            Progreso\r\n");
      out.write("                        </span>\r\n");
      out.write("\r\n");
      out.write("                        <strong>\r\n");
      out.write("                            ");
      out.print( tarea.getProgreso() );
      out.write("%\r\n");
      out.write("                        </strong>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"barra-progreso\">\r\n");
      out.write("\r\n");
      out.write("                        <div\r\n");
      out.write("                                class=\"barra-progreso-valor\"\r\n");
      out.write("                                style=\"width: ");
      out.print( tarea.getProgreso() );
      out.write("%\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- ==============================================\r\n");
      out.write("                     SUBTAREAS\r\n");
      out.write("                     ============================================== -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"subtareas\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"seccion-tarea-titulo\">\r\n");
      out.write("\r\n");
      out.write("                        <span>\r\n");
      out.write("                            ✓\r\n");
      out.write("                        </span>\r\n");
      out.write("\r\n");
      out.write("                        <strong>\r\n");
      out.write("                            Subtareas\r\n");
      out.write("                        </strong>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");

                        List<SubTask> subtareas =
                                subtareasPorTarea != null
                                        ? subtareasPorTarea.get(
                                        tarea.getId()
                                )
                                        : null;
                    
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");
 if (subtareas != null
                            && !subtareas.isEmpty()) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <ul class=\"lista-subtareas\">\r\n");
      out.write("\r\n");
      out.write("                        ");
 for (SubTask subTask :
                                subtareas) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"subtarea\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <form\r\n");
      out.write("                                    action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/subtareas\"\r\n");
      out.write("                                    method=\"post\">\r\n");
      out.write("\r\n");
      out.write("                                <input\r\n");
      out.write("                                        type=\"hidden\"\r\n");
      out.write("                                        name=\"accion\"\r\n");
      out.write("                                        value=\"toggle\">\r\n");
      out.write("\r\n");
      out.write("                                <input\r\n");
      out.write("                                        type=\"hidden\"\r\n");
      out.write("                                        name=\"id\"\r\n");
      out.write("                                        value=\"");
      out.print( subTask.getIdSubtarea() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                                <input\r\n");
      out.write("                                        type=\"checkbox\"\r\n");
      out.write("                                        onchange=\"this.form.submit()\"\r\n");
      out.write("                                    ");
      out.print( subTask.isCompletada()
                                                        ? "checked"
                                                        : "" );
      out.write(">\r\n");
      out.write("\r\n");
      out.write("                            </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <span class=\"");
      out.print( subTask.isCompletada()
                                            ? "completada"
                                            : "" );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                                        ");
      out.print( subTask.getDescripcion() );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                    </span>\r\n");
      out.write("\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <p class=\"sin-datos\">\r\n");
      out.write("                        No hay subtareas.\r\n");
      out.write("                    </p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- ==============================================\r\n");
      out.write("                     RECORDATORIOS\r\n");
      out.write("                     ============================================== -->\r\n");
      out.write("\r\n");
      out.write("                ");

                    List<Reminder> recordatorios =
                            recordatoriosPorTarea != null
                                    ? recordatoriosPorTarea.get(
                                    tarea.getId()
                            )
                                    : null;
                
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                ");
 if (recordatorios != null
                        && !recordatorios.isEmpty()) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"recordatorios\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"seccion-tarea-titulo\">\r\n");
      out.write("\r\n");
      out.write("                            <span>\r\n");
      out.write("                                ⏰\r\n");
      out.write("                            </span>\r\n");
      out.write("\r\n");
      out.write("                        <strong>\r\n");
      out.write("                            Recordatorios\r\n");
      out.write("                        </strong>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <ul>\r\n");
      out.write("\r\n");
      out.write("                        ");
 for (Reminder reminder :
                                recordatorios) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <li>\r\n");
      out.write("\r\n");
      out.write("                            <strong>\r\n");
      out.write("                                ");
      out.print( reminder.getFechaHora() );
      out.write("\r\n");
      out.write("                            </strong>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            ");
 if (reminder.getMensaje() != null
                                    && !reminder.getMensaje().isBlank()) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <span>\r\n");
      out.write("                                            ");
      out.print( reminder.getMensaje() );
      out.write("\r\n");
      out.write("                                        </span>\r\n");
      out.write("\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </article>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- ====================================================\r\n");
      out.write("             SIN TAREAS\r\n");
      out.write("             ==================================================== -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"sin-tareas\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"sin-tareas-icono\">\r\n");
      out.write("                ✓\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <h3>\r\n");
      out.write("                No tienes tareas todavía\r\n");
      out.write("            </h3>\r\n");
      out.write("\r\n");
      out.write("            <p>\r\n");
      out.write("                Crea tu primera tarea usando el formulario de arriba.\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("        src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/tareas.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
