/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.24
 * Generated at: 2026-08-14 02:24:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.time.format.DateTimeFormatter;
import org.todolist.model.TimeLog;

public final class timelog_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("org.todolist.model.TimeLog");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("    <title>Registro de tiempo - ToDo List</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\"\r\n");
      out.write("          href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/timelog.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h1>Mis registros de tiempo</h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ============================================================\r\n");
      out.write("     FORMULARIO CREAR / EDITAR\r\n");
      out.write("     ============================================================ -->\r\n");
      out.write("\r\n");

    TimeLog timelogEditar =
            (TimeLog) request.getAttribute("timelogEditar");

    DateTimeFormatter formato =
            DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"formulario-timelog\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 if (timelogEditar == null) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ========================================================\r\n");
      out.write("         CREAR REGISTRO\r\n");
      out.write("         ======================================================== -->\r\n");
      out.write("\r\n");
      out.write("    <h2>Agregar registro de tiempo</h2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/timelog\"\r\n");
      out.write("          method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <input type=\"hidden\"\r\n");
      out.write("               name=\"accion\"\r\n");
      out.write("               value=\"crear\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"campo\">\r\n");
      out.write("\r\n");
      out.write("            <label for=\"inicio\">\r\n");
      out.write("                Fecha y hora de inicio\r\n");
      out.write("            </label>\r\n");
      out.write("\r\n");
      out.write("            <input\r\n");
      out.write("                    type=\"datetime-local\"\r\n");
      out.write("                    id=\"inicio\"\r\n");
      out.write("                    name=\"inicio\"\r\n");
      out.write("                    required>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"campo\">\r\n");
      out.write("\r\n");
      out.write("            <label for=\"fin\">\r\n");
      out.write("                Fecha y hora de fin\r\n");
      out.write("            </label>\r\n");
      out.write("\r\n");
      out.write("            <input\r\n");
      out.write("                    type=\"datetime-local\"\r\n");
      out.write("                    id=\"fin\"\r\n");
      out.write("                    name=\"fin\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"campo\">\r\n");
      out.write("\r\n");
      out.write("            <label for=\"idTarea\">\r\n");
      out.write("                ID de tarea\r\n");
      out.write("            </label>\r\n");
      out.write("\r\n");
      out.write("            <input\r\n");
      out.write("                    type=\"number\"\r\n");
      out.write("                    id=\"idTarea\"\r\n");
      out.write("                    name=\"idTarea\"\r\n");
      out.write("                    min=\"1\"\r\n");
      out.write("                    required>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <button type=\"submit\">\r\n");
      out.write("            Agregar registro\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ========================================================\r\n");
      out.write("         EDITAR REGISTRO\r\n");
      out.write("         ======================================================== -->\r\n");
      out.write("\r\n");
      out.write("    <h2>Editar registro de tiempo</h2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/timelog\"\r\n");
      out.write("          method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <input type=\"hidden\"\r\n");
      out.write("               name=\"accion\"\r\n");
      out.write("               value=\"actualizar\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <input type=\"hidden\"\r\n");
      out.write("               name=\"idRegistro\"\r\n");
      out.write("               value=\"");
      out.print( timelogEditar.getIdRegistro() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"campo\">\r\n");
      out.write("\r\n");
      out.write("            <label for=\"inicio\">\r\n");
      out.write("                Fecha y hora de inicio\r\n");
      out.write("            </label>\r\n");
      out.write("\r\n");
      out.write("            <input\r\n");
      out.write("                    type=\"datetime-local\"\r\n");
      out.write("                    id=\"inicio\"\r\n");
      out.write("                    name=\"inicio\"\r\n");
      out.write("                    value=\"");
      out.print( timelogEditar.getInicio() != null
                            ? timelogEditar.getInicio().format(formato)
                            : "" );
      out.write("\"\r\n");
      out.write("                    required>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"campo\">\r\n");
      out.write("\r\n");
      out.write("            <label for=\"fin\">\r\n");
      out.write("                Fecha y hora de fin\r\n");
      out.write("            </label>\r\n");
      out.write("\r\n");
      out.write("            <input\r\n");
      out.write("                    type=\"datetime-local\"\r\n");
      out.write("                    id=\"fin\"\r\n");
      out.write("                    name=\"fin\"\r\n");
      out.write("                    value=\"");
      out.print( timelogEditar.getFin() != null
                            ? timelogEditar.getFin().format(formato)
                            : "" );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"campo\">\r\n");
      out.write("\r\n");
      out.write("            <label for=\"idTarea\">\r\n");
      out.write("                ID de tarea\r\n");
      out.write("            </label>\r\n");
      out.write("\r\n");
      out.write("            <input\r\n");
      out.write("                    type=\"number\"\r\n");
      out.write("                    id=\"idTarea\"\r\n");
      out.write("                    name=\"idTarea\"\r\n");
      out.write("                    min=\"1\"\r\n");
      out.write("                    value=\"");
      out.print( timelogEditar.getIdTarea() );
      out.write("\"\r\n");
      out.write("                    required>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <button type=\"submit\">\r\n");
      out.write("            Guardar cambios\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/timelog\">\r\n");
      out.write("            Cancelar\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ============================================================\r\n");
      out.write("     LISTA DE REGISTROS\r\n");
      out.write("     ============================================================ -->\r\n");
      out.write("\r\n");
      out.write("<section class=\"lista-timelog\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <h2>Registros de tiempo</h2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

        List<TimeLog> timelogs =
                (List<TimeLog>) request.getAttribute("timelogs");
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 if (timelogs == null || timelogs.isEmpty()) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <p>\r\n");
      out.write("        No hay registros de tiempo.\r\n");
      out.write("    </p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"timelogs\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 for (TimeLog registro : timelogs) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <article class=\"timelog\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <h3>\r\n");
      out.write("                Registro #");
      out.print( registro.getIdRegistro() );
      out.write("\r\n");
      out.write("            </h3>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- =================================================\r\n");
      out.write("                 INFORMACIÓN DEL REGISTRO\r\n");
      out.write("                 ================================================= -->\r\n");
      out.write("\r\n");
      out.write("            <p>\r\n");
      out.write("\r\n");
      out.write("                <strong>Tarea:</strong>\r\n");
      out.write("\r\n");
      out.write("                ");
      out.print( registro.getIdTarea() );
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <p>\r\n");
      out.write("\r\n");
      out.write("                <strong>Inicio:</strong>\r\n");
      out.write("\r\n");
      out.write("                ");
      out.print( registro.getInicio() != null
                        ? registro.getInicio().format(
                                DateTimeFormatter.ofPattern(
                                        "dd/MM/yyyy HH:mm"
                                )
                        )
                        : "Sin inicio" );
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <p>\r\n");
      out.write("\r\n");
      out.write("                <strong>Fin:</strong>\r\n");
      out.write("\r\n");
      out.write("                ");
      out.print( registro.getFin() != null
                        ? registro.getFin().format(
                                DateTimeFormatter.ofPattern(
                                        "dd/MM/yyyy HH:mm"
                                )
                        )
                        : "En curso" );
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <p>\r\n");
      out.write("\r\n");
      out.write("                <strong>Duración:</strong>\r\n");
      out.write("\r\n");
      out.write("                ");
      out.print( registro.getDuracionMinutos() );
      out.write("\r\n");
      out.write("                minutos\r\n");
      out.write("\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- =================================================\r\n");
      out.write("                 ESTADO\r\n");
      out.write("                 ================================================= -->\r\n");
      out.write("\r\n");
      out.write("            <p>\r\n");
      out.write("\r\n");
      out.write("                <strong>Estado:</strong>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                ");
 if (registro.estaActivo()) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <span class=\"estado-activo\">\r\n");
      out.write("                        En curso\r\n");
      out.write("                    </span>\r\n");
      out.write("\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <span class=\"estado-finalizado\">\r\n");
      out.write("                        Finalizado\r\n");
      out.write("                    </span>\r\n");
      out.write("\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- =================================================\r\n");
      out.write("                 ACCIONES\r\n");
      out.write("                 ================================================= -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"acciones\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- =============================================\r\n");
      out.write("                     INICIAR / FINALIZAR\r\n");
      out.write("                     ============================================= -->\r\n");
      out.write("\r\n");
      out.write("                ");
 if (!registro.estaActivo()) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/timelog\"\r\n");
      out.write("                      method=\"post\"\r\n");
      out.write("                      style=\"display:inline;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"hidden\"\r\n");
      out.write("                           name=\"accion\"\r\n");
      out.write("                           value=\"iniciar\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"hidden\"\r\n");
      out.write("                           name=\"idTarea\"\r\n");
      out.write("                           value=\"");
      out.print( registro.getIdTarea() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"submit\">\r\n");
      out.write("\r\n");
      out.write("                        Iniciar conteo\r\n");
      out.write("\r\n");
      out.write("                    </button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/timelog\"\r\n");
      out.write("                      method=\"post\"\r\n");
      out.write("                      style=\"display:inline;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"hidden\"\r\n");
      out.write("                           name=\"accion\"\r\n");
      out.write("                           value=\"finalizar\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"hidden\"\r\n");
      out.write("                           name=\"idRegistro\"\r\n");
      out.write("                           value=\"");
      out.print( registro.getIdRegistro() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"submit\">\r\n");
      out.write("\r\n");
      out.write("                        Finalizar conteo\r\n");
      out.write("\r\n");
      out.write("                    </button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- =============================================\r\n");
      out.write("                     EDITAR\r\n");
      out.write("                     ============================================= -->\r\n");
      out.write("\r\n");
      out.write("                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/timelog\"\r\n");
      out.write("                      method=\"get\"\r\n");
      out.write("                      style=\"display:inline;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"hidden\"\r\n");
      out.write("                           name=\"accion\"\r\n");
      out.write("                           value=\"editar\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"hidden\"\r\n");
      out.write("                           name=\"id\"\r\n");
      out.write("                           value=\"");
      out.print( registro.getIdRegistro() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"submit\">\r\n");
      out.write("\r\n");
      out.write("                        Editar\r\n");
      out.write("\r\n");
      out.write("                    </button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- =============================================\r\n");
      out.write("                     ELIMINAR\r\n");
      out.write("                     ============================================= -->\r\n");
      out.write("\r\n");
      out.write("                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/timelog\"\r\n");
      out.write("                      method=\"post\"\r\n");
      out.write("                      style=\"display:inline;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"hidden\"\r\n");
      out.write("                           name=\"accion\"\r\n");
      out.write("                           value=\"eliminar\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"hidden\"\r\n");
      out.write("                           name=\"id\"\r\n");
      out.write("                           value=\"");
      out.print( registro.getIdRegistro() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <button\r\n");
      out.write("                            type=\"submit\"\r\n");
      out.write("                            onclick=\"return confirm(\r\n");
      out.write("                                '¿Está seguro de eliminar este registro de tiempo?'\r\n");
      out.write("                            );\">\r\n");
      out.write("\r\n");
      out.write("                        Eliminar\r\n");
      out.write("\r\n");
      out.write("                    </button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </article>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/timelog.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
